### ISSUE TITLE
HTML in Card Description

### ISSUE THREAD

**Issue by OlofMalmstrom** [qlik-oss/sn-org-chart#193]
After upgrading Qlik sense and the Vis-bundle I can no longer use HTML formatting in the Card Description of the org chart. I have a simple HTML table to display a set of KPI's.

A simple test with just a < b > gave a bold text, but now the extension writes out the "< b >" instead of changing to bold... 

Not sure what the last version this worked on but at least it worked on version 0.10.1 
Now on 0.13.0 it's not working

Is this a bug or an intended change?

**Comment by niekvanstaveren** [comment]
Hi @OlofMalmstrom,

This was an intended change. HTML is not aloud in the card for security reasons.

**Comment by OlofMalmstrom** [comment]
Ok thanks for the answer. It would have been great to use just the basic functions like <table> <b> etc... But I understand...
