### ISSUE TITLE
New Feature Request > HTML Tooltip Expression

### ISSUE THREAD

**Issue by scheav** [qlik-oss/sn-org-chart#246]
Hello @LiKang6688 , thank you for allowing me to post feature request here. It would be great if we can add a new feature HTML Tooltip Expression. This will give us more flexibility to provide more context (picture, employee attributes,...using HTML code) when hover each card. Thank you for your consideration

**Comment by niekvanstaveren** [comment]
@scheav These kind of things normally go through product management. The best way to get attention for this is to go through ideation. See here https://community.qlik.com/t5/Ideation/ct-p/qlik-product-insight
I will close this issue since this is mainly a feature request
