### ISSUE TITLE
Remove useState from options

### ISSUE THREAD

**Issue by Caele** [qlik-oss/sn-org-chart#75]
The useState part below should not be needed, https://github.com/qlik-oss/sn-org-chart/blob/master/src/index.js#L47 
```
const options = useOptions();
const [opts] = useState(options);
````

**Comment by niekvanstaveren** [comment]
Don't we already have that?

**Comment by Caele** [comment]
I misspelled a bit, what I mean is that we do useState(options) and then never set that state. So we should be able to use options directly instead. Unless there is a specific reason, which from my point of view could only be because of a bug somewhere.
Added this as a github issue as it isn't a priority, but didn't want it to get lost. Will look at adding more of these as I find oddities in the code.

**Comment by niekvanstaveren** [comment]
Fixed in this PR https://github.com/qlik-oss/sn-org-chart/commit/31618de8b68dc74f392294a12547037e270817bd
